version: "3.9"
services:
  myservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_URLS: http://+:80
      AllowedOrigins: http://localhost:8100
      SignalRHubUri: hub/v1/notifications